install:
  - ps: .\scripts\install.ps1

platform:
  - x86
  - x64

environment:
  matrix:
    - RUST_VERSION: 1.1.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

build: false

test_script:
  - cargo test
